version: "3"

services:
  main:
    image: "gia/streamyolo"
    build: .
    ports:
      - "8501:8501"
    command: streamlit run --browser.serverAddress 0.0.0.0 moviesdemo.py
    # volumes:
    #   - "OUT:IN"
